// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDab_pxdOECISGiucQ7wKAWgleApSww8jM',
    appId: '1:813200800580:web:2d2f49beaad6fbd2b2b511',
    messagingSenderId: '813200800580',
    projectId: 'kigali-city-services-dir-1dff9',
    authDomain: 'kigali-city-services-dir-1dff9.firebaseapp.com',
    storageBucket: 'kigali-city-services-dir-1dff9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvbeOfWzu7kyKyvjycwnx4hOJLsYaeS7I',
    appId: '1:813200800580:android:ae7c27ea8ae71975b2b511',
    messagingSenderId: '813200800580',
    projectId: 'kigali-city-services-dir-1dff9',
    storageBucket: 'kigali-city-services-dir-1dff9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX-enPSugqd56MGTiAlLQ-hV_Aje8G8w8',
    appId: '1:813200800580:ios:542396107e5cad45b2b511',
    messagingSenderId: '813200800580',
    projectId: 'kigali-city-services-dir-1dff9',
    storageBucket: 'kigali-city-services-dir-1dff9.firebasestorage.app',
    iosBundleId: 'com.example.kigaliCityDirectory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX-enPSugqd56MGTiAlLQ-hV_Aje8G8w8',
    appId: '1:813200800580:ios:542396107e5cad45b2b511',
    messagingSenderId: '813200800580',
    projectId: 'kigali-city-services-dir-1dff9',
    storageBucket: 'kigali-city-services-dir-1dff9.firebasestorage.app',
    iosBundleId: 'com.example.kigaliCityDirectory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDab_pxdOECISGiucQ7wKAWgleApSww8jM',
    appId: '1:813200800580:web:78cb37f44d13feacb2b511',
    messagingSenderId: '813200800580',
    projectId: 'kigali-city-services-dir-1dff9',
    authDomain: 'kigali-city-services-dir-1dff9.firebaseapp.com',
    storageBucket: 'kigali-city-services-dir-1dff9.firebasestorage.app',
  );
}
